import { useState, type FormEvent } from 'react';
import { Pencil, Plus, Target, Trash2, X } from 'lucide-react';
import { formatDate, money, type Goal } from '../data';
import { decimal } from './form';
const freshGoal=()=>({name:'',target_amount:'',saved_amount:'0',due_on:''});

export function GoalsPanel({goals,onSave,onDelete}:{goals:Goal[];onSave:(goal:Goal)=>void;onDelete:(id:string)=>void}){
  const [editing,setEditing]=useState<Goal|null>(null);const [open,setOpen]=useState(false);const [form,setForm]=useState(freshGoal);
  function openForm(goal?:Goal){setEditing(goal??null);setForm(goal?{name:goal.name,target_amount:String(goal.target_amount),saved_amount:String(goal.saved_amount),due_on:goal.due_on??''}:freshGoal());setOpen(true)}
  function submit(e:FormEvent){e.preventDefault();const target=decimal(form.target_amount),saved=decimal(form.saved_amount);if(!Number.isFinite(target)||target<=0||!Number.isFinite(saved)||saved<0)return;onSave({id:editing?.id??crypto.randomUUID(),name:form.name.trim().slice(0,80),target_amount:Math.round(target*100)/100,saved_amount:Math.round(saved*100)/100,due_on:form.due_on||null});setOpen(false)}
  return <><div className="feature-intro"><div><span className="section-kicker">TUS PLANES</span><h2>Objetivos que se ven avanzar.</h2><p>Reserva una parte de lo que ya tienes. El ahorro asignado no se suma otra vez a tu patrimonio.</p></div><button className="primary-button" onClick={()=>openForm()}><Plus size={17}/> Crear objetivo</button></div><div className="feature-grid three">{goals.map(goal=>{const pct=Math.min(100,Math.round(Number(goal.saved_amount)/Number(goal.target_amount)*100));return <article className="card goal-tile" key={goal.id}><div className="tile-head"><div className="feature-icon"><Target size={20}/></div><button className="icon-button" aria-label={`Eliminar ${goal.name}`} onClick={()=>{if(confirm(`¿Eliminar el objetivo «${goal.name}»?`))onDelete(goal.id)}}><Trash2 size={16}/></button></div><h3>{goal.name}</h3><strong className="feature-value">{money(Number(goal.saved_amount))}</strong><p>de {money(Number(goal.target_amount))} · {pct}% conseguido</p><div className="progress goal-progress"><span style={{width:`${pct}%`}}/></div>{goal.due_on&&<small>Fecha objetivo: {formatDate(goal.due_on)}</small>}<button className="text-link" onClick={()=>openForm(goal)}><Pencil size={14}/> Actualizar progreso</button></article>})}<button className="add-budget-tile" onClick={()=>openForm()}><Plus size={25}/><strong>Nuevo objetivo</strong><span>Un viaje, un colchón, una casa…</span></button></div>{open&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="goal-title"><div className="modal-heading"><h2 id="goal-title">{editing?'Editar objetivo':'Nuevo objetivo'}</h2><button className="icon-button" onClick={()=>setOpen(false)}><X size={20}/></button></div><form onSubmit={submit}><label>Nombre<input required maxLength={80} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Por ejemplo, fondo de emergencia"/></label><div className="form-row"><label>Meta (€)<input required type="number" min="0.01" step="0.01" value={form.target_amount} onChange={e=>setForm({...form,target_amount:e.target.value})}/></label><label>Ya reservado (€)<input required type="number" min="0" step="0.01" value={form.saved_amount} onChange={e=>setForm({...form,saved_amount:e.target.value})}/></label></div><label>Fecha objetivo (opcional)<input type="date" value={form.due_on} onChange={e=>setForm({...form,due_on:e.target.value})}/></label><p className="form-hint">Este importe es una etiqueta de ahorro sobre tu dinero disponible, no una cuenta adicional.</p><button className="primary-button form-submit">Guardar objetivo</button></form></div></div>}</>
}
