import { useState, type ChangeEvent } from 'react';
import { Check, CircleAlert, UploadCloud, X } from 'lucide-react';
import { CATEGORIES, accountName, money, type AccountSetting, type AccountType, type Transaction } from '../data';
import { parseFile, type ImportPreview, type ColumnMap, type Field, type SignMode } from '../import';

export function ImportDialog({existing,accounts,onConfirm,onClose}:{existing:Transaction[];accounts:AccountSetting[];onConfirm:(values:Transaction[])=>void;onClose:()=>void}){
  const [file,setFile]=useState<File|null>(null),[account,setAccount]=useState<AccountType>('bank');
  const [preview,setPreview]=useState<ImportPreview|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState<Set<string>>(new Set()),[columns,setColumns]=useState<ColumnMap>({}),[categoryEdits,setCategoryEdits]=useState<Record<string,string>>({});
  const [sheet,setSheet]=useState(''),[header,setHeader]=useState(0),[signMode,setSignMode]=useState<SignMode>('signed');
  async function load(nextFile:File|null,nextAccount=account,manual=false){if(!nextFile)return;setFile(nextFile);setLoading(true);setError('');
    try{const result=await parseFile(nextFile,existing,nextAccount,manual?{sheet,header,columns,signMode}:{});
      setPreview(result);setSelected(new Set(result.rows.filter(r=>r.selected).map(r=>r.id)));setCategoryEdits({});
      if(!manual){const first=result.sheets.find(s=>s.name===result.rows[0]?.sheet)??result.sheets[0];setSheet(first?.name??'');setHeader(first?.header??0);setColumns(first?.suggested??{});setSignMode('signed')}
    }catch(reason){setPreview(null);setError(reason instanceof Error?reason.message:'No se pudo leer el archivo')}finally{setLoading(false)}
  }
  const ready=preview?.rows.filter(r=>selected.has(r.id)&&r.valid&&!r.duplicate)??[];
  const invalid=preview?.rows.filter(r=>!r.valid)??[],duplicates=preview?.rows.filter(r=>r.duplicate)??[];
  const active=preview?.sheets.find(s=>s.name===sheet)??preview?.sheets[0];
  function finish(){if(!ready.length||preview?.needsMapping)return;onConfirm(ready.map(r=>({id:r.id,kind:r.kind,amount:r.amount,description:r.description,category:categoryEdits[r.id]?.trim().slice(0,60)||r.category,occurred_on:r.occurred_on,account,import_key:r.import_key})));onClose()}
  const fields:Array<[Field,string]>=[['date','Fecha de operación o finalización'],['startDate','Fecha de inicio (respaldo)'],['amount','Importe con signo'],['debit','Cargo / debe'],['credit','Abono / haber'],['fee','Comisión'],['description','Descripción'],['description2','Detalle adicional'],['merchant','Comercio'],['category','Categoría del banco'],['type','Tipo de movimiento'],['reference','ID de operación'],['currency','Divisa'],['state','Estado']];
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="modal-heading"><div><span className="section-kicker">IMPORTAR ARCHIVO</span><h2 id="import-title">De la hoja a tus gráficos.</h2></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={20}/></button></div>
    <p className="feature-copy">Descarga los movimientos desde tu banco en CSV o Excel. Se leen en tu dispositivo: revisa importes, fechas y comercios antes de guardarlos. Solo se sincronizan los movimientos que confirmes.</p>
    <label className="file-drop"><UploadCloud size={25}/><strong>{file?.name??'Elige el archivo de movimientos'}</strong><span>Archivos .xlsx, .csv o .tsv · hasta 8 MB</span><input type="file" accept=".xlsx,.csv,.tsv" onChange={(e:ChangeEvent<HTMLInputElement>)=>void load(e.target.files?.[0]??null)}/></label>
    <div className="import-account"><label>Asignar movimientos a <select value={account} onChange={e=>{const value=e.target.value;setAccount(value);if(file)void load(file,value)}}>{accounts.map(a=><option key={a.account} value={a.account}>{accountName(a.account,accounts)}</option>)}</select></label></div>
    {loading&&<p className="feature-copy">Leyendo y comprobando filas…</p>}{error&&<div className="notice" role="alert">{error}</div>}
    {preview&&<><div className="import-overview"><span><strong>{preview.rows.length}</strong> encontrados</span><span><strong>{ready.length}</strong> listos</span><span><strong>{duplicates.length}</strong> posibles duplicados</span><span><strong>{invalid.length}</strong> por revisar</span></div>
      {preview.openingBalance!==undefined&&<div className="import-warning"><CircleAlert size={17}/><span>Saldo inicial detectado: {money(preview.openingBalance)}. No se añade como ingreso. Si ya incluye estos movimientos, no lo pongas como saldo inicial en Cuentas.</span></div>}
      {(preview.needsMapping||active)&&<details className="import-mapping" open={preview.needsMapping}><summary>{preview.needsMapping?'Revisa las columnas y confirma cómo leer los importes':'Ajustar columnas o sentido de los importes'}</summary>
        {preview.warning&&<p className="import-warning">{preview.warning}</p>}
        {preview.sheets.length>1&&<label>Hoja <select value={sheet} onChange={e=>{const next=preview.sheets.find(s=>s.name===e.target.value);setSheet(e.target.value);setHeader(next?.header??0);setColumns(next?.suggested??{})}}>{preview.sheets.map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</select></label>}
        {active&&<label>Fila de encabezados <select value={header} onChange={e=>{const number=Number(e.target.value);setHeader(number);setColumns({})}}>{active.choices.map(choice=><option key={choice.index} value={choice.index}>Fila {choice.index+1}: {choice.sample}</option>)}</select></label>}
        {active&&<div className="mapping-form">{fields.map(([field,label])=><label key={field}>{label}<select value={columns[field]??''} onChange={e=>setColumns(prev=>({...prev,[field]:e.target.value===''?undefined:Number(e.target.value)}))}><option value="">— No usar —</option>{active.headers.map((h,i)=><option key={i} value={i}>{i+1}. {h||'(sin nombre)'}</option>)}</select></label>)}</div>}
        <label>Interpretación del importe (si no hay cargos y abonos separados)<select value={signMode} onChange={e=>setSignMode(e.target.value as SignMode)}><option value="signed">Negativo = gasto; positivo = ingreso</option><option value="expenses">Todos son gastos</option><option value="income">Todos son ingresos</option></select></label>
        <button className="secondary-button" disabled={loading||!file} onClick={()=>void load(file,account,true)}>Aplicar y revisar vista previa</button>
      </details>}
      {preview.needsMapping&&<p className="import-warning" role="status">Confirma las columnas y el sentido del importe para habilitar la importación.</p>}
      {!!preview.rows.length&&<><datalist id="import-categories">{[...new Set([...CATEGORIES,'Salario',...preview.rows.map(r=>r.category)])].map(category=><option key={category} value={category}/>)}</datalist><div className="import-table-wrap"><table className="import-table"><thead><tr><th>Incluir</th><th>Fecha</th><th>Movimiento y comercio</th><th>Categoría</th><th>Importe</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.id} className={!row.valid||row.duplicate?'muted-row':''}><td><input type="checkbox" aria-label={'Importar fila '+row.line+' de '+row.sheet} checked={selected.has(row.id)} disabled={!row.valid||row.duplicate||preview.needsMapping} onChange={e=>setSelected(current=>{const next=new Set(current);if(e.target.checked)next.add(row.id);else next.delete(row.id);return next})}/></td><td>{row.occurred_on||'—'}</td><td><strong>{row.merchant?row.merchant+' · ':''}{row.description||'Sin descripción'}</strong><small>{row.reason??(row.duplicate?'Posible duplicado':row.sheet+' · fila '+row.line)}</small></td><td><input className="import-category-input" aria-label={'Categoría fila '+row.line} list="import-categories" maxLength={60} disabled={!row.valid||row.duplicate} value={categoryEdits[row.id]??row.category} onChange={e=>setCategoryEdits(prev=>({...prev,[row.id]:e.target.value}))}/></td><td className={row.kind==='income'?'positive':''}>{row.kind==='income'?'+':'−'}{money(row.amount)}</td></tr>)}</tbody></table></div>
        <p className="import-footnote">Las categorías son sugerencias: puedes corregirlas aquí. Las filas inválidas y los importes de otras divisas no se guardan. Comprueba los movimientos repetidos antes de confirmar.</p><button className="primary-button form-submit" disabled={!ready.length||preview.needsMapping} onClick={finish}><Check size={18}/> Importar {ready.length} movimientos</button></>}
    </>}
  </div></div>
}
